version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gaming-marketing-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gaming_marketing
      MYSQL_USER: mcpuser
      MYSQL_PASSWORD: mcppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - gaming-marketing-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  gaming-marketing-network:
    driver: bridge
